// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	dto "github.com/vanhieudn01/service-test/grpc-gen/dto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0xa5, 0x04, 0x33,
	0x53, 0x72, 0xf4, 0x53, 0x4a, 0xf2, 0x41, 0x18, 0x22, 0x67, 0xe4, 0xc0, 0xc5, 0x9e, 0x5a, 0x91,
	0x98, 0x5b, 0x90, 0x93, 0x2a, 0x64, 0xca, 0xc5, 0xe5, 0x91, 0x9a, 0x93, 0x93, 0x1f, 0x9e, 0x5f,
	0x94, 0x93, 0x22, 0x24, 0xa4, 0x07, 0x52, 0x94, 0x92, 0x58, 0x92, 0xa8, 0x07, 0x16, 0x0d, 0x4a,
	0x2d, 0x94, 0x12, 0xc6, 0x10, 0x2b, 0x2e, 0x48, 0x62, 0x03, 0x1b, 0x64, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0xcf, 0x36, 0x57, 0x75, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleClient is the client API for Example service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleClient interface {
	HelloWorld(ctx context.Context, in *dto.HelloReq, opts ...grpc.CallOption) (*dto.HelloResp, error)
}

type exampleClient struct {
	cc *grpc.ClientConn
}

func NewExampleClient(cc *grpc.ClientConn) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) HelloWorld(ctx context.Context, in *dto.HelloReq, opts ...grpc.CallOption) (*dto.HelloResp, error) {
	out := new(dto.HelloResp)
	err := c.cc.Invoke(ctx, "/service.example/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServer is the server API for Example service.
type ExampleServer interface {
	HelloWorld(context.Context, *dto.HelloReq) (*dto.HelloResp, error)
}

func RegisterExampleServer(s *grpc.Server, srv ExampleServer) {
	s.RegisterService(&_Example_serviceDesc, srv)
}

func _Example_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.example/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).HelloWorld(ctx, req.(*dto.HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Example_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _Example_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
